/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AShare {
        "files": File[];
        "text": string;
        "url": string;
        "urlTitle": string;
    }
}
declare global {
    interface HTMLAShareElement extends Components.AShare, HTMLStencilElement {
    }
    var HTMLAShareElement: {
        prototype: HTMLAShareElement;
        new (): HTMLAShareElement;
    };
    interface HTMLElementTagNameMap {
        "a-share": HTMLAShareElement;
    }
}
declare namespace LocalJSX {
    interface AShare {
        "files"?: File[];
        "onHasShared"?: (event: CustomEvent<boolean>) => void;
        "text"?: string;
        "url"?: string;
        "urlTitle"?: string;
    }
    interface IntrinsicElements {
        "a-share": AShare;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "a-share": LocalJSX.AShare & JSXBase.HTMLAttributes<HTMLAShareElement>;
        }
    }
}
